### PR TITLE
Rename PORT to BACKEND_PORT and introduce FRONTEND_PORT

### PR DESCRIPTION
**Pull request by fabfuel**
Squashed commits of pull request: https://github.com/tutumcloud/tutum-docker-clusterproxy/pull/24

### CODE REVIEW

**Comment by tifayuki** [comment]
Merged.

Thank you

**Comment by buehler** [comment]
Hey there

I saw your PR but also discovered that the documentation is not up to date. In your PR the documentation is updated but on the github main page there are no examples for BACKEND_PORT and FRONTEND_PORT :-(

Cheers
Chris

**Comment by tifayuki** [comment]
@buehler 
The PR is for version 1, and deprecated in the current version.

**Comment by buehler** [comment]
oh :O
how will it be managed in the future?

**Pull request merged**
