### PR TITLE
Configurable rsyslog destination

### PR DESCRIPTION
**Pull request by motin**
As suggested in https://github.com/tutumcloud/tutum-docker-clusterproxy/issues/25

### CODE REVIEW

**Comment by ryansroberts** [comment]
+1 on this, nice work

**Comment by motin** [comment]
Thanks :)
@tifayuki Let me know if this PR is ok, if yes let me fix a typo and squash the commits before merge :)

**Comment by tifayuki** [comment]
LGTM
Thank you @motin

**Comment by motin** [comment]
Typo fixed and commits squashed

**Comment by kytwb** [comment]
@motin I'm trying to send this to loggly syslog endpoint which looks like this: `syslog://logs-01.loggly.com:514?structured_data=df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058`. Any ideas?

**Comment by motin** [comment]
@kytwb Probably something like:
```
docker run -it --env RSYSLOG_DESTINATION='logs-01.loggly.com:514?structured_data=df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058' -p 80:80 --link web1:web1 --link web2:web2 tutum/haproxy
```

**Comment by kytwb** [comment]
@motin results in:

```
[ALERT] 151/052138 (11) : parsing [/etc/haproxy/haproxy.cfg:2] : 'log' : port ranges and offsets are not allowed in 'logs-01.loggly.com:514?structured_data=df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058'
[ALERT] 151/052138 (11) : parsing [/etc/haproxy/haproxy.cfg:3] : 'log' : port ranges and offsets are not allowed in 'logs-01.loggly.com:514?structured_data=df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058'
[ALERT] 151/052138 (11) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 151/052138 (11) : Fatal errors found in configuration.
```

**Comment by motin** [comment]
@kytwb I was naive. Sorry about that. According to [loggly remote syslog docs](https://www.loggly.com/docs/rsyslog-manual-configuration/) Loggly you should send the logs to "logs-01.loggly.com:514" and then make sure that the log format includes the information about the token and tag. 
I could not find specific information on how to configure haproxy specifically for Loggly, but when you have such confirmation that log-format needs to be customizable for haproxy, you might want to create a new issue for adding a new LOG_FORMAT Docker configuration variable to this repo.

**Pull request merged**
