### PR TITLE
Stats

### PR DESCRIPTION
**Pull request by motin**
Fixes https://github.com/tutumcloud/tutum-docker-clusterproxy/issues/40

### CODE REVIEW

**Comment by motin** [comment]
One thing I'd like to change is the default stats port, set to 8088 currently and shows up as "omniorb" in the tutum interface. What would be a better stats port?

**Comment by fermayo** [comment]
Maybe use port 8080? @tifayuki ?

**Comment by tifayuki** [comment]
@fermayo I think `8088` is good. `8080` may be useful when chaining haproxy together. As 8080 is another popular web port, I will not use it for stats reporting.

**Comment by tifayuki** [comment]
@motin
Talked to @fermayo, and we think 9000 is a good option. Could you please change it and squash the commits?

Thank you

**Comment by motin** [comment]
Port 9000 is the default for PHP-FPM, which at least I actively load-balance using tutum/haproxy. Maybe we should find one yet not listed on http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers?

**Comment by tifayuki** [comment]
@motin 
Can we do port `1936`?

**Comment by motin** [comment]
@tifayuki [Great choice](http://serverfault.com/questions/169181/how-to-set-up-stats-for-haproxy)! I'll update and squash

**Pull request merged**
